#! /bin/bash

ls Testdir/

read -p "Enter Table you want to read" TableName

if ! [[ -f Testdir/$TableName ]]
then
echo "Wrong Table name"
source ./TableMenue.sh
fi

echo Do you want to Read The whole table or select some rows ? 
echo [1] Read whole table
echo [2] Select 

select choice in 1 2

do
case $choice in
1)
cat Testdir/$TableName
source ./TableMenue.sh
;;
2)

read -p "Enter field you want to search for" fname
read -p "Enter field value" val

fn=`awk 'BEGIN{FS=":"} {if ($1 == "'$fname'") print NR }' Testdir/schema_f1`
fn=$((fn-1))

awk 'BEGIN{FS=":"} { if($'$fn' == "'$val'") print $0 }' Testdir/f1
source ./TableMenue.sh
;;
*)
echo Wrong input
;;

esac
done




