#! /bin/bash
ls Testdir/

read -p "Enter the Table you want to rename " oldname



if [[ -f Testdir/$oldname ]]

then
read -p "Enter new name " newname
mv Testdir/$oldname Testdir/$newname
echo Table renamed successfully !!

else
echo Wrong table name

fi
