#! /usr/bin/bash

DB=$1

echo See all available tables files:
ls DBs/$DB | grep -v '^schema_' # List all files not starting with schema_ (table files only)

read -p "Enter the Table you want to rename : " oldname

if [[ -f DBs/$DB/$oldname ]]; then
    read -p "Enter new name : " NewName
    mv DBs/$DB/schema_$oldname DBs/$DB/schema_$NewName
    mv DBs/$DB/$oldname DBs/$DB/$NewName
    echo Table renamed successfully with its schema file !!
    
else
    echo Wrong table name  
fi


source ./TableScripts/TableMenu.sh
