#! /bin/bash


read -p "Enter Field name :  " fname
read -p "Enter value you want to update : " oldValue
read -p "Enter updated value : " newValue 


fn=`awk 'BEGIN{FS=":"} {if ($1 == "'$fname'") print NR }' Testdir/schema_f1`
fn=$((fn-1))

nr=`awk 'BEGIN{FS=":"} {if ($'$fn' == '$oldValue') print NR }' testTable`


arr=($(awk -F':' 'BEGIN{OFS=":"} { if(NR == "'$nr'") $'$fn' = "'$newValue'" } 1' testTable))

cat /dev/null > testTable # delete file content

for el in "${arr[@]}"
do
echo $el >> testTable 
done
